### ISSUE TITLE
While starting local cluster with extraMounts option I got [ FailedScheduling, NodeNotReady, FailedMount ]

### ISSUE THREAD

**Issue by iamtodor** [kubernetes-sigs/kind#2669]
Firstly, please accept my apologies for the title, feel free to rename it to make it more understandable.

**What happened**:
When I start the cluster with a mount the node is not starting.

**What you expected to happen**:
Everything is fine, works as it supposed to be

**How to reproduce it (as minimally and precisely as possible)**:
I start the cluster with the following script:
<details>

<summary>start-cluster.sh</summary>

```bash
#!/bin/sh
set -o errexit

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5001'
if [ "$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
  docker run \
    -d --restart=always -p "127.0.0.1:${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster \
--image kindest/node:v1.19.11 \
--config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:5000"]
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/itodorenko/programming/work/projects/airflow_dags/
        containerPath: /data_dags
EOF

# connect the registry to the cluster network if not already connected
if [ "$(docker inspect -f='{{json .NetworkSettings.Networks.kind}}' "${reg_name}")" = 'null' ]; then
  docker network connect "kind" "${reg_name}"
fi

# Document the local registry
# https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:${reg_port}"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
EOF
```

</details>

It's pretty much the same as https://kind.sigs.k8s.io/docs/user/local-registry/ expect:
- add `image kindest/node:v1.19.11`
- add mount:
    ```
    nodes:
    - role: control-plane
        extraMounts:
        - hostPath: /Users/itodorenko/programming/work/projects/airflow_dags/
            containerPath: /data_dags
    ```

Then I run a command to get all the events from starting k8s cluster

<details>

<summary>kubectl get events --sort-by='.metadata.creationTimestamp' -A</summary>

```
>>> kubectl get events --sort-by='.metadata.creationTimestamp' -A
NAMESPACE            LAST SEEN   TYPE      REASON                    OBJECT                                         MESSAGE
default              3m23s       Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              3m23s       Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              3m23s       Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
kube-system          3m11s       Normal    LeaderElection            lease/kube-controller-manager                  kind-control-plane_0fa39692-52c9-48f8-9202-a84252ec87a3 became leader
kube-system          3m11s       Normal    LeaderElection            endpoints/kube-controller-manager              kind-control-plane_0fa39692-52c9-48f8-9202-a84252ec87a3 became leader
kube-system          3m11s       Normal    LeaderElection            endpoints/kube-scheduler                       kind-control-plane_6812dd86-9351-4f8f-ad1e-bba5f7c6737b became leader
kube-system          3m11s       Normal    LeaderElection            lease/kube-scheduler                           kind-control-plane_6812dd86-9351-4f8f-ad1e-bba5f7c6737b became leader
default              3m7s        Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
default              3m7s        Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              3m7s        Normal    Starting                  node/kind-control-plane                        Starting kubelet.
default              3m7s        Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              3m7s        Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
kube-system          2m55s       Normal    SuccessfulCreate          daemonset/kindnet                              Created pod: kindnet-kthxr
local-path-storage   2m52s       Warning   FailedScheduling          pod/local-path-provisioner-547f784dff-slfdq    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          2m55s       Normal    SuccessfulCreate          daemonset/kube-proxy                           Created pod: kube-proxy-46mlh
kube-system          2m47s       Warning   FailedScheduling          pod/coredns-f9fd979d6-9mw9x                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          2m47s       Warning   FailedScheduling          pod/coredns-f9fd979d6-drvv6                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          2m55s       Normal    Pulled                    pod/kube-proxy-46mlh                           Container image "k8s.gcr.io/kube-proxy:v1.19.11" already present on machine
local-path-storage   2m55s       Normal    SuccessfulCreate          replicaset/local-path-provisioner-547f784dff   Created pod: local-path-provisioner-547f784dff-slfdq
kube-system          2m55s       Normal    Scheduled                 pod/kube-proxy-46mlh                           Successfully assigned kube-system/kube-proxy-46mlh to kind-control-plane
local-path-storage   2m55s       Normal    ScalingReplicaSet         deployment/local-path-provisioner              Scaled up replica set local-path-provisioner-547f784dff to 1
kube-system          2m55s       Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-drvv6
kube-system          2m55s       Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-9mw9x
kube-system          2m55s       Normal    ScalingReplicaSet         deployment/coredns                             Scaled up replica set coredns-f9fd979d6 to 2
default              2m55s       Normal    RegisteredNode            node/kind-control-plane                        Node kind-control-plane event: Registered Node kind-control-plane in Controller
kube-system          2m55s       Warning   NodeNotReady              pod/kube-apiserver-kind-control-plane          Node is not ready
kube-system          2m55s       Normal    Scheduled                 pod/kindnet-kthxr                              Successfully assigned kube-system/kindnet-kthxr to kind-control-plane
kube-system          2m54s       Normal    Pulled                    pod/kindnet-kthxr                              Container image "docker.io/kindest/kindnetd:v20210326-1e038dc5" already present on machine
kube-system          2m53s       Normal    Started                   pod/kindnet-kthxr                              Started container kindnet-cni
kube-system          2m53s       Normal    Created                   pod/kindnet-kthxr                              Created container kindnet-cni
default              2m53s       Normal    Starting                  node/kind-control-plane                        Starting kube-proxy.
kube-system          2m53s       Normal    Created                   pod/kube-proxy-46mlh                           Created container kube-proxy
kube-system          2m53s       Normal    Started                   pod/kube-proxy-46mlh                           Started container kube-proxy
default              2m47s       Normal    NodeReady                 node/kind-control-plane                        Node kind-control-plane status is now: NodeReady
local-path-storage   2m47s       Normal    Scheduled                 pod/local-path-provisioner-547f784dff-slfdq    Successfully assigned local-path-storage/local-path-provisioner-547f784dff-slfdq to kind-control-plane
local-path-storage   2m45s       Normal    Pulled                    pod/local-path-provisioner-547f784dff-slfdq    Container image "docker.io/rancher/local-path-provisioner:v0.0.14" already present on machine
local-path-storage   2m45s       Warning   FailedMount               pod/local-path-provisioner-547f784dff-slfdq    MountVolume.SetUp failed for volume "config-volume" : failed to sync configmap cache: timed out waiting for the condition
local-path-storage   2m45s       Warning   FailedMount               pod/local-path-provisioner-547f784dff-slfdq    MountVolume.SetUp failed for volume "local-path-provisioner-service-account-token-25fx4" : failed to sync secret cache: timed out waiting for the condition
local-path-storage   2m44s       Normal    Created                   pod/local-path-provisioner-547f784dff-slfdq    Created container local-path-provisioner
local-path-storage   2m44s       Normal    Started                   pod/local-path-provisioner-547f784dff-slfdq    Started container local-path-provisioner
local-path-storage   2m44s       Normal    LeaderElection            endpoints/rancher.io-local-path                local-path-provisioner-547f784dff-slfdq_1e7f54c7-559f-44de-a427-da4b7d52f826 became leader
kube-system          2m42s       Normal    Scheduled                 pod/coredns-f9fd979d6-drvv6                    Successfully assigned kube-system/coredns-f9fd979d6-drvv6 to kind-control-plane
kube-system          2m42s       Normal    Scheduled                 pod/coredns-f9fd979d6-9mw9x                    Successfully assigned kube-system/coredns-f9fd979d6-9mw9x to kind-control-plane
kube-system          2m41s       Normal    Created                   pod/coredns-f9fd979d6-drvv6                    Created container coredns
kube-system          2m41s       Normal    Started                   pod/coredns-f9fd979d6-9mw9x                    Started container coredns
kube-system          2m41s       Normal    Pulled                    pod/coredns-f9fd979d6-9mw9x                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          2m41s       Normal    Started                   pod/coredns-f9fd979d6-drvv6                    Started container coredns
kube-system          2m41s       Normal    Pulled                    pod/coredns-f9fd979d6-drvv6                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          2m41s       Normal    Created                   pod/coredns-f9fd979d6-9mw9x                    Created container coredns
```

</details>

Here I noticed a few warnings:
```
local-path-storage   2m52s       Warning   FailedScheduling          pod/local-path-provisioner-547f784dff-slfdq    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          2m47s       Warning   FailedScheduling          pod/coredns-f9fd979d6-9mw9x                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          2m47s       Warning   FailedScheduling          pod/coredns-f9fd979d6-drvv6                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          2m55s       Warning   NodeNotReady              pod/kube-apiserver-kind-control-plane          Node is not ready
local-path-storage   2m45s       Warning   FailedMount               pod/local-path-provisioner-547f784dff-slfdq    MountVolume.SetUp failed for volume "config-volume" : failed to sync configmap cache: timed out waiting for the condition
local-path-storage   2m45s       Warning   FailedMount               pod/local-path-provisioner-547f784dff-slfdq    MountVolume.SetUp failed for volume "local-path-provisioner-service-account-token-25fx4" : failed to sync secret cache: timed out waiting for the condition
```

I don't understand what might be the problem with mount:
```
>>> ll /Users/itodorenko/programming/work/projects/airflow_dags/
total 24
-rw-r--r--   1 itodorenko  staff   692B Mar  3 18:09 README.md
-rw-r--r--   1 itodorenko  staff     0B Feb 10 12:09 __init__.py
drwxr-xr-x  27 itodorenko  staff   864B Mar  2 20:20 data_dags
-rw-r--r--   1 itodorenko  staff   521B Mar  7 16:18 main.py
-rw-r--r--   1 itodorenko  staff   202B Mar  7 16:27 requirements.txt
drwxr-xr-x   7 itodorenko  staff   224B Feb 14 12:39 venv
```

**Environment:**
```
>>> kind version
kind v0.11.1 go1.16.4 darwin/amd64

>>> kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-27T23:47:11Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

>>> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: MY35:G6TD:KDL6:GDDY:AUUK:UW2O:N3SG:HRJ7:PDZR:5YWP:L3LB:4CAR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

>>> sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

**Comment by BenTheElder** [comment]
Your sample config has incorrect indentation on the container path?

Have you tested this without the mount but otherwise everything the same?

**Comment by iamtodor** [comment]
@BenTheElder 
`Your sample config has incorrect indentation on the container path?` - I'm so sorry, I am not sure if I follow your question :(((
`Have you tested this without the mount but otherwise everything the same?`
Yeah, with the following config I still get warnings
<details>
<summary>local registry with kindest/node:v1.19.11</summary>

```
#!/bin/sh
set -o errexit

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5001'
if [ "$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
  docker run \
    -d --restart=always -p "127.0.0.1:${reg_port}:5000" --name "${reg_name}" \
    registry:2
fi

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster \
--image kindest/node:v1.19.11 \
--config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:${reg_port}"]
    endpoint = ["http://${reg_name}:5000"]
EOF

# connect the registry to the cluster network if not already connected
if [ "$(docker inspect -f='{{json .NetworkSettings.Networks.kind}}' "${reg_name}")" = 'null' ]; then
  docker network connect "kind" "${reg_name}"
fi

# Document the local registry
# https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:${reg_port}"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
EOF
```

</details>

Here is the output of `kubectl get events --sort-by='.metadata.creationTimestamp' -A`. I am still getting `local-path-storage   102s        Warning   FailedScheduling          pod/local-path-provisioner-547f784dff-88lkt    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.` 

<details>

```
>>> kubectl get events --sort-by='.metadata.creationTimestamp' -A
NAMESPACE            LAST SEEN   TYPE      REASON                    OBJECT                                         MESSAGE
default              2m19s       Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              2m19s       Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              2m19s       Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
kube-system          2m7s        Normal    LeaderElection            lease/kube-controller-manager                  kind-control-plane_c0ebb1e2-05b1-4807-8d02-0770c1fcd52f became leader
kube-system          2m7s        Normal    LeaderElection            endpoints/kube-controller-manager              kind-control-plane_c0ebb1e2-05b1-4807-8d02-0770c1fcd52f became leader
kube-system          2m6s        Normal    LeaderElection            endpoints/kube-scheduler                       kind-control-plane_37c011d2-d545-4538-80c4-48109a757eb3 became leader
kube-system          2m6s        Normal    LeaderElection            lease/kube-scheduler                           kind-control-plane_37c011d2-d545-4538-80c4-48109a757eb3 became leader
default              2m2s        Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              2m2s        Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              2m2s        Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
default              2m2s        Normal    Starting                  node/kind-control-plane                        Starting kubelet.
default              2m2s        Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
kube-system          111s        Normal    SuccessfulCreate          daemonset/kube-proxy                           Created pod: kube-proxy-mbt92
local-path-storage   102s        Warning   FailedScheduling          pod/local-path-provisioner-547f784dff-88lkt    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          102s        Warning   FailedScheduling          pod/coredns-f9fd979d6-mxtpz                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
local-path-storage   111s        Normal    SuccessfulCreate          replicaset/local-path-provisioner-547f784dff   Created pod: local-path-provisioner-547f784dff-88lkt
kube-system          102s        Warning   FailedScheduling          pod/coredns-f9fd979d6-vv5sz                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          111s        Normal    Scheduled                 pod/kube-proxy-mbt92                           Successfully assigned kube-system/kube-proxy-mbt92 to kind-control-plane
kube-system          111s        Normal    ScalingReplicaSet         deployment/coredns                             Scaled up replica set coredns-f9fd979d6 to 2
local-path-storage   111s        Normal    ScalingReplicaSet         deployment/local-path-provisioner              Scaled up replica set local-path-provisioner-547f784dff to 1
default              111s        Normal    RegisteredNode            node/kind-control-plane                        Node kind-control-plane event: Registered Node kind-control-plane in Controller
kube-system          111s        Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-vv5sz
kube-system          111s        Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-mxtpz
kube-system          111s        Normal    Scheduled                 pod/kindnet-97dk9                              Successfully assigned kube-system/kindnet-97dk9 to kind-control-plane
kube-system          111s        Normal    SuccessfulCreate          daemonset/kindnet                              Created pod: kindnet-97dk9
kube-system          110s        Normal    Pulled                    pod/kube-proxy-mbt92                           Container image "k8s.gcr.io/kube-proxy:v1.19.11" already present on machine
kube-system          110s        Normal    Pulled                    pod/kindnet-97dk9                              Container image "docker.io/kindest/kindnetd:v20210326-1e038dc5" already present on machine
kube-system          109s        Normal    Created                   pod/kube-proxy-mbt92                           Created container kube-proxy
kube-system          109s        Normal    Started                   pod/kube-proxy-mbt92                           Started container kube-proxy
default              108s        Normal    Starting                  node/kind-control-plane                        Starting kube-proxy.
kube-system          107s        Normal    Started                   pod/kindnet-97dk9                              Started container kindnet-cni
kube-system          107s        Normal    Created                   pod/kindnet-97dk9                              Created container kindnet-cni
default              102s        Normal    NodeReady                 node/kind-control-plane                        Node kind-control-plane status is now: NodeReady
kube-system          97s         Normal    Pulled                    pod/coredns-f9fd979d6-mxtpz                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          97s         Normal    Scheduled                 pod/coredns-f9fd979d6-vv5sz                    Successfully assigned kube-system/coredns-f9fd979d6-vv5sz to kind-control-plane
kube-system          97s         Normal    Pulled                    pod/coredns-f9fd979d6-vv5sz                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          97s         Normal    Scheduled                 pod/coredns-f9fd979d6-mxtpz                    Successfully assigned kube-system/coredns-f9fd979d6-mxtpz to kind-control-plane
local-path-storage   97s         Normal    Scheduled                 pod/local-path-provisioner-547f784dff-88lkt    Successfully assigned local-path-storage/local-path-provisioner-547f784dff-88lkt to kind-control-plane
local-path-storage   97s         Normal    Pulled                    pod/local-path-provisioner-547f784dff-88lkt    Container image "docker.io/rancher/local-path-provisioner:v0.0.14" already present on machine
kube-system          96s         Normal    Created                   pod/coredns-f9fd979d6-mxtpz                    Created container coredns
kube-system          96s         Normal    Started                   pod/coredns-f9fd979d6-mxtpz                    Started container coredns
local-path-storage   96s         Normal    Created                   pod/local-path-provisioner-547f784dff-88lkt    Created container local-path-provisioner
local-path-storage   96s         Normal    Started                   pod/local-path-provisioner-547f784dff-88lkt    Started container local-path-provisioner
kube-system          96s         Normal    Created                   pod/coredns-f9fd979d6-vv5sz                    Created container coredns
kube-system          96s         Normal    Started                   pod/coredns-f9fd979d6-vv5sz                    Started container coredns
local-path-storage   96s         Normal    LeaderElection            endpoints/rancher.io-local-path                local-path-provisioner-547f784dff-88lkt_46e94886-f22f-4d7b-a408-d9d5af28f291 became leader
```

</details>

**Comment by iamtodor** [comment]
@BenTheElder I run the simple command `kind create cluster --image kindest/node:v1.19.7` and I still get this issue: `0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.`

<details>

<summary>output kubectl get events --sort-by='.metadata.creationTimestamp' -A</summary>

```
kubectl get events --sort-by='.metadata.creationTimestamp' -A
NAMESPACE            LAST SEEN   TYPE      REASON                    OBJECT                                         MESSAGE
default              40s         Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
kube-system          29s         Normal    LeaderElection            endpoints/kube-controller-manager              kind-control-plane_df497697-b5d2-4dfe-98dd-05d844a105b0 became leader
default              40s         Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              40s         Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
kube-system          29s         Normal    LeaderElection            lease/kube-controller-manager                  kind-control-plane_df497697-b5d2-4dfe-98dd-05d844a105b0 became leader
default              27s         Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              27s         Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              27s         Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              27s         Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
default              27s         Normal    Starting                  node/kind-control-plane                        Starting kubelet.
kube-system          27s         Normal    LeaderElection            endpoints/kube-scheduler                       kind-control-plane_a4bde2d9-cfa2-4e2a-8eeb-67155b72f30c became leader
kube-system          27s         Normal    LeaderElection            lease/kube-scheduler                           kind-control-plane_a4bde2d9-cfa2-4e2a-8eeb-67155b72f30c became leader
kube-system          12s         Normal    SuccessfulCreate          daemonset/kube-proxy                           Created pod: kube-proxy-ssp5z
kube-system          12s         Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-b57zf
kube-system          12s         Normal    ScalingReplicaSet         deployment/coredns                             Scaled up replica set coredns-f9fd979d6 to 2
kube-system          12s         Normal    Scheduled                 pod/kindnet-mjwhs                              Successfully assigned kube-system/kindnet-mjwhs to kind-control-plane
local-path-storage   12s         Warning   FailedScheduling          pod/local-path-provisioner-78776bfc44-l64wk    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          12s         Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-kpg5g
kube-system          10s         Warning   FailedScheduling          pod/coredns-f9fd979d6-kpg5g                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          12s         Warning   FailedScheduling          pod/coredns-f9fd979d6-b57zf                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          12s         Normal    SuccessfulCreate          daemonset/kindnet                              Created pod: kindnet-mjwhs
local-path-storage   12s         Normal    SuccessfulCreate          replicaset/local-path-provisioner-78776bfc44   Created pod: local-path-provisioner-78776bfc44-l64wk
default              12s         Normal    RegisteredNode            node/kind-control-plane                        Node kind-control-plane event: Registered Node kind-control-plane in Controller
kube-system          12s         Normal    Scheduled                 pod/kube-proxy-ssp5z                           Successfully assigned kube-system/kube-proxy-ssp5z to kind-control-plane
local-path-storage   12s         Normal    ScalingReplicaSet         deployment/local-path-provisioner              Scaled up replica set local-path-provisioner-78776bfc44 to 1
kube-system          11s         Warning   FailedMount               pod/kindnet-mjwhs                              MountVolume.SetUp failed for volume "kindnet-token-tsf25" : failed to sync secret cache: timed out waiting for the condition
kube-system          11s         Warning   FailedMount               pod/kube-proxy-ssp5z                           MountVolume.SetUp failed for volume "kube-proxy-token-hbfwb" : failed to sync secret cache: timed out waiting for the condition
kube-system          10s         Normal    Pulled                    pod/kindnet-mjwhs                              Container image "kindest/kindnetd:v20210119-d5ef916d" already present on machine
kube-system          10s         Normal    Pulled                    pod/kube-proxy-ssp5z                           Container image "k8s.gcr.io/kube-proxy:v1.19.7" already present on machine
kube-system          9s          Normal    Created                   pod/kube-proxy-ssp5z                           Created container kube-proxy
default              9s          Normal    Starting                  node/kind-control-plane                        Starting kube-proxy.
kube-system          9s          Normal    Started                   pod/kube-proxy-ssp5z                           Started container kube-proxy
kube-system          8s          Normal    Started                   pod/kindnet-mjwhs                              Started container kindnet-cni
kube-system          8s          Normal    Created                   pod/kindnet-mjwhs                              Created container kindnet-cni
```

<details>

**Comment by iamtodor** [comment]
I also tried to run a pure cluster with mount:
```bash
cat <<EOF | kind create cluster \
--image kindest/node:v1.19.11 \
--config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/itodorenko/programming/work/projects/airflow_dags/
        containerPath: /data_dags

EOF
```

And I got the same warnings:
- FailedScheduling
- FailedMount

<details>

<summary>output from kubectl get events --sort-by='.metadata.creationTimestamp' -A</summary>

```
>>> kubectl get events --sort-by='.metadata.creationTimestamp' -A
NAMESPACE            LAST SEEN   TYPE      REASON                    OBJECT                                         MESSAGE
default              71s         Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              71s         Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              71s         Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
kube-system          60s         Normal    LeaderElection            endpoints/kube-scheduler                       kind-control-plane_498599ad-9da6-4e02-8f99-e592d9e0671c became leader
kube-system          60s         Normal    LeaderElection            lease/kube-controller-manager                  kind-control-plane_75f5ddd0-0f44-46e1-8139-3bc3c7903a8b became leader
kube-system          60s         Normal    LeaderElection            lease/kube-scheduler                           kind-control-plane_498599ad-9da6-4e02-8f99-e592d9e0671c became leader
kube-system          60s         Normal    LeaderElection            endpoints/kube-controller-manager              kind-control-plane_75f5ddd0-0f44-46e1-8139-3bc3c7903a8b became leader
default              56s         Normal    Starting                  node/kind-control-plane                        Starting kubelet.
default              55s         Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              55s         Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
default              55s         Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              55s         Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
local-path-storage   35s         Warning   FailedScheduling          pod/local-path-provisioner-547f784dff-m7nf7    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          35s         Warning   FailedScheduling          pod/coredns-f9fd979d6-lb6pb                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
local-path-storage   44s         Normal    SuccessfulCreate          replicaset/local-path-provisioner-547f784dff   Created pod: local-path-provisioner-547f784dff-m7nf7
kube-system          44s         Normal    SuccessfulCreate          daemonset/kube-proxy                           Created pod: kube-proxy-xs5n2
kube-system          35s         Warning   FailedScheduling          pod/coredns-f9fd979d6-sjpw6                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          44s         Normal    Pulled                    pod/kube-proxy-xs5n2                           Container image "k8s.gcr.io/kube-proxy:v1.19.11" already present on machine
kube-system          44s         Normal    ScalingReplicaSet         deployment/coredns                             Scaled up replica set coredns-f9fd979d6 to 2
kube-system          44s         Normal    Scheduled                 pod/kube-proxy-xs5n2                           Successfully assigned kube-system/kube-proxy-xs5n2 to kind-control-plane
local-path-storage   44s         Normal    ScalingReplicaSet         deployment/local-path-provisioner              Scaled up replica set local-path-provisioner-547f784dff to 1
kube-system          44s         Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-sjpw6
kube-system          44s         Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-lb6pb
default              44s         Normal    RegisteredNode            node/kind-control-plane                        Node kind-control-plane event: Registered Node kind-control-plane in Controller
kube-system          44s         Normal    Scheduled                 pod/kindnet-4l8dt                              Successfully assigned kube-system/kindnet-4l8dt to kind-control-plane
kube-system          44s         Normal    Pulled                    pod/kindnet-4l8dt                              Container image "docker.io/kindest/kindnetd:v20210326-1e038dc5" already present on machine
kube-system          44s         Normal    SuccessfulCreate          daemonset/kindnet                              Created pod: kindnet-4l8dt
kube-system          43s         Normal    Created                   pod/kube-proxy-xs5n2                           Created container kube-proxy
kube-system          43s         Normal    Started                   pod/kube-proxy-xs5n2                           Started container kube-proxy
kube-system          42s         Normal    Created                   pod/kindnet-4l8dt                              Created container kindnet-cni
default              42s         Normal    Starting                  node/kind-control-plane                        Starting kube-proxy.
kube-system          42s         Normal    Started                   pod/kindnet-4l8dt                              Started container kindnet-cni
default              35s         Normal    NodeReady                 node/kind-control-plane                        Node kind-control-plane status is now: NodeReady
kube-system          27s         Normal    Scheduled                 pod/coredns-f9fd979d6-sjpw6                    Successfully assigned kube-system/coredns-f9fd979d6-sjpw6 to kind-control-plane
kube-system          27s         Normal    Pulled                    pod/coredns-f9fd979d6-lb6pb                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          27s         Normal    Pulled                    pod/coredns-f9fd979d6-sjpw6                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
local-path-storage   27s         Normal    Scheduled                 pod/local-path-provisioner-547f784dff-m7nf7    Successfully assigned local-path-storage/local-path-provisioner-547f784dff-m7nf7 to kind-control-plane
kube-system          27s         Normal    Scheduled                 pod/coredns-f9fd979d6-lb6pb                    Successfully assigned kube-system/coredns-f9fd979d6-lb6pb to kind-control-plane
kube-system          26s         Normal    Created                   pod/coredns-f9fd979d6-lb6pb                    Created container coredns
kube-system          26s         Normal    Started                   pod/coredns-f9fd979d6-lb6pb                    Started container coredns
local-path-storage   26s         Warning   FailedMount               pod/local-path-provisioner-547f784dff-m7nf7    MountVolume.SetUp failed for volume "config-volume" : failed to sync configmap cache: timed out waiting for the condition
kube-system          26s         Normal    Created                   pod/coredns-f9fd979d6-sjpw6                    Created container coredns
kube-system          26s         Normal    Started                   pod/coredns-f9fd979d6-sjpw6                    Started container coredns
local-path-storage   25s         Normal    Started                   pod/local-path-provisioner-547f784dff-m7nf7    Started container local-path-provisioner
local-path-storage   25s         Normal    Created                   pod/local-path-provisioner-547f784dff-m7nf7    Created container local-path-provisioner
local-path-storage   25s         Normal    LeaderElection            endpoints/rancher.io-local-path                local-path-provisioner-547f784dff-m7nf7_6516ed67-8234-4c26-ac61-1082dd03c388 became leader
local-path-storage   25s         Normal    Pulled                    pod/local-path-provisioner-547f784dff-m7nf7    Container image "docker.io/rancher/local-path-provisioner:v0.0.14" already present on machine
```

</details>

**Comment by BenTheElder** [comment]
can you upload `kind export logs` after just creating the 1.19 cluster? can you try kind v0.12.0?

it seems your minimum reproducer is actually `kind create cluster --image kindest/node:v1.19.7`, so let's see why that isn't working. the pod events don't tell us much, but the node logs probably will.

**Comment by iamtodor** [comment]
@BenTheElder I need the specific 1.19 version for my development

All the content was uploaded
[docker-info.txt](https://github.com/kubernetes-sigs/kind/files/8221435/docker-info.txt)
[kind-version.txt](https://github.com/kubernetes-sigs/kind/files/8221437/kind-version.txt)
[kind-control-plane.zip](https://github.com/kubernetes-sigs/kind/files/8221439/kind-control-plane.zip)

```
>>> kind export logs
Exporting logs for cluster "kind" to:
/private/var/folders/5m/nv7xp6tx39qbmr56yvtqn_z80000gp/T/790382202
>>> cd /private/var/folders/5m/nv7xp6tx39qbmr56yvtqn_z80000gp/T/790382202
>>> tree
.
├── docker-info.txt
├── kind-control-plane
│   ├── alternatives.log
│   ├── containerd.log
│   ├── containers
│   │   ├── etcd-kind-control-plane_kube-system_etcd-1c78d62ccdb805ac7cab8a0824383d128388ba6cffdacbe81481c1722e0f3a3a.log
│   │   ├── kube-apiserver-kind-control-plane_kube-system_kube-apiserver-6ed73c235f179ebe251525294403f6f658976616d1770e28953bfc0f32d1dd6f.log
│   │   ├── kube-controller-manager-kind-control-plane_kube-system_kube-controller-manager-02bd49cb8b46f053cb880d904cbf5d0abafeede504117b9b7f9a320287522e71.log
│   │   └── kube-scheduler-kind-control-plane_kube-system_kube-scheduler-49ee06e5a96f4ba6b6e8371d169de02e521ffafe2c845451ca6572c5c24b682d.log
│   ├── inspect.json
│   ├── journal.log
│   ├── kubelet.log
│   ├── kubernetes-version.txt
│   ├── pods
│   │   ├── kube-system_etcd-kind-control-plane_cf4c58b46b076f92a91a604fa6503368
│   │   │   └── etcd
│   │   │       └── 0.log
│   │   ├── kube-system_kube-apiserver-kind-control-plane_7f25a2d44685c02590d70fd06aa93ecd
│   │   │   └── kube-apiserver
│   │   │       └── 0.log
│   │   ├── kube-system_kube-controller-manager-kind-control-plane_3c8f9d792c2c456053ffd9ea52aaca93
│   │   │   └── kube-controller-manager
│   │   │       └── 0.log
│   │   └── kube-system_kube-scheduler-kind-control-plane_57b58b3eb5589cb745c50233392349fb
│   │       └── kube-scheduler
│   │           └── 0.log
│   └── serial.log
├── kind-control-plane.zip
└── kind-version.txt

11 directories, 18 files
```

**Comment by BenTheElder** [comment]
I'm referring to the kind binary v0.12.0 which is newer than the version you are using, not the node image which you are using unpinned at v1.19.11 which will now be the image we published for v0.12.0

I will check these logs when I get a chance (on mobile atm)

**Comment by iamtodor** [comment]
@BenTheElder same with kind v0.12.0

<details>

<summary>kubectl get events --sort-by='.metadata.creationTimestamp' -A</summary>

```
>>> kubectl get events --sort-by='.metadata.creationTimestamp' -A
NAMESPACE            LAST SEEN   TYPE      REASON                    OBJECT                                         MESSAGE
kube-system          39s         Normal    LeaderElection            endpoints/kube-controller-manager              kind-control-plane_f389be84-e95a-45ab-a1fe-c9584ce99b15 became leader
kube-system          39s         Normal    LeaderElection            lease/kube-controller-manager                  kind-control-plane_f389be84-e95a-45ab-a1fe-c9584ce99b15 became leader
default              38s         Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              38s         Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              38s         Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
default              38s         Normal    Starting                  node/kind-control-plane                        Starting kubelet.
kube-system          38s         Normal    LeaderElection            lease/kube-scheduler                           kind-control-plane_7d2207b4-4fcb-4e2c-8808-d5e2c4d1171f became leader
default              38s         Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
kube-system          38s         Normal    LeaderElection            endpoints/kube-scheduler                       kind-control-plane_7d2207b4-4fcb-4e2c-8808-d5e2c4d1171f became leader
kube-system          23s         Normal    SuccessfulCreate          daemonset/kindnet                              Created pod: kindnet-m8nd9
local-path-storage   8s          Warning   FailedScheduling          pod/local-path-provisioner-78776bfc44-ssnhz    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          23s         Normal    SuccessfulCreate          daemonset/kube-proxy                           Created pod: kube-proxy-hm6df
kube-system          8s          Warning   FailedScheduling          pod/coredns-f9fd979d6-8cv7x                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          8s          Warning   FailedScheduling          pod/coredns-f9fd979d6-p8xkp                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
default              23s         Normal    RegisteredNode            node/kind-control-plane                        Node kind-control-plane event: Registered Node kind-control-plane in Controller
kube-system          23s         Normal    Scheduled                 pod/kube-proxy-hm6df                           Successfully assigned kube-system/kube-proxy-hm6df to kind-control-plane
local-path-storage   23s         Normal    SuccessfulCreate          replicaset/local-path-provisioner-78776bfc44   Created pod: local-path-provisioner-78776bfc44-ssnhz
local-path-storage   23s         Normal    ScalingReplicaSet         deployment/local-path-provisioner              Scaled up replica set local-path-provisioner-78776bfc44 to 1
kube-system          23s         Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-p8xkp
kube-system          23s         Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-8cv7x
kube-system          23s         Normal    ScalingReplicaSet         deployment/coredns                             Scaled up replica set coredns-f9fd979d6 to 2
kube-system          23s         Normal    Scheduled                 pod/kindnet-m8nd9                              Successfully assigned kube-system/kindnet-m8nd9 to kind-control-plane
kube-system          23s         Warning   NodeNotReady              pod/kube-apiserver-kind-control-plane          Node is not ready
kube-system          22s         Normal    Pulled                    pod/kube-proxy-hm6df                           Container image "k8s.gcr.io/kube-proxy:v1.19.7" already present on machine
kube-system          22s         Normal    Pulled                    pod/kindnet-m8nd9                              Container image "kindest/kindnetd:v20210119-d5ef916d" already present on machine
kube-system          21s         Normal    Started                   pod/kindnet-m8nd9                              Started container kindnet-cni
kube-system          21s         Normal    Created                   pod/kindnet-m8nd9                              Created container kindnet-cni
default              21s         Normal    Starting                  node/kind-control-plane                        Starting kube-proxy.
kube-system          21s         Normal    Created                   pod/kube-proxy-hm6df                           Created container kube-proxy
kube-system          21s         Normal    Started                   pod/kube-proxy-hm6df                           Started container kube-proxy
default              8s          Normal    NodeReady                 node/kind-control-plane                        Node kind-control-plane status is now: NodeReady
kube-system          4s          Normal    Scheduled                 pod/coredns-f9fd979d6-8cv7x                    Successfully assigned kube-system/coredns-f9fd979d6-8cv7x to kind-control-plane
kube-system          4s          Normal    Scheduled                 pod/coredns-f9fd979d6-p8xkp                    Successfully assigned kube-system/coredns-f9fd979d6-p8xkp to kind-control-plane
local-path-storage   4s          Normal    Scheduled                 pod/local-path-provisioner-78776bfc44-ssnhz    Successfully assigned local-path-storage/local-path-provisioner-78776bfc44-ssnhz to kind-control-plane
kube-system          3s          Normal    Started                   pod/coredns-f9fd979d6-8cv7x                    Started container coredns
kube-system          3s          Normal    Created                   pod/coredns-f9fd979d6-8cv7x                    Created container coredns
kube-system          3s          Normal    Pulled                    pod/coredns-f9fd979d6-8cv7x                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
local-path-storage   3s          Normal    LeaderElection            endpoints/rancher.io-local-path                local-path-provisioner-78776bfc44-ssnhz_b633b7da-8585-4135-bf25-094a28b0996f became leader
kube-system          3s          Normal    Pulled                    pod/coredns-f9fd979d6-p8xkp                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
local-path-storage   3s          Normal    Created                   pod/local-path-provisioner-78776bfc44-ssnhz    Created container local-path-provisioner
local-path-storage   3s          Normal    Started                   pod/local-path-provisioner-78776bfc44-ssnhz    Started container local-path-provisioner
kube-system          3s          Normal    Created                   pod/coredns-f9fd979d6-p8xkp                    Created container coredns
kube-system          3s          Normal    Started                   pod/coredns-f9fd979d6-p8xkp                    Started container coredns
local-path-storage   3s          Normal    Pulled                    pod/local-path-provisioner-78776bfc44-ssnhz    Container image "rancher/local-path-provisioner:v0.0.14" already present on machine
```

</details>

```
kind version
kind v0.12.0 go1.17.8 darwin/amd64
```

**Comment by iamtodor** [comment]
@BenTheElder Here are new logs from `kind export logs`
[docker-info.txt](https://github.com/kubernetes-sigs/kind/files/8222850/docker-info.txt)
[kind-version.txt](https://github.com/kubernetes-sigs/kind/files/8222852/kind-version.txt)
[kind-control-plane.zip](https://github.com/kubernetes-sigs/kind/files/8222854/kind-control-plane.zip)

**Comment by iamtodor** [comment]
@BenTheElder I have a few updates.
Regarding a FailedMount: I didn't add this mount path in `Docker->Preferences->Resources->File Sharing`.
I totally understand it is obvious, but still. And now I just noticed it was mentioned right here https://github.com/kubernetes-sigs/kind/blob/main/site/content/docs/user/configuration.md?plain=1#L286

I still have the issue with `FailedScheduling`.

Once I add mount here is the output from `kubectl get events --sort-by='.metadata.creationTimestamp' -A`

<details>

```
>>> kubectl get events --sort-by='.metadata.creationTimestamp' -A
NAMESPACE            LAST SEEN   TYPE      REASON                    OBJECT                                         MESSAGE
default              3m35s       Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              3m35s       Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              3m35s       Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              3m35s       Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
kube-system          3m22s       Normal    LeaderElection            lease/kube-controller-manager                  kind-control-plane_3fc668a7-5d83-4cb5-8a8c-b1b1338cbbf0 became leader
kube-system          3m22s       Normal    LeaderElection            endpoints/kube-controller-manager              kind-control-plane_3fc668a7-5d83-4cb5-8a8c-b1b1338cbbf0 became leader
kube-system          3m22s       Normal    LeaderElection            lease/kube-scheduler                           kind-control-plane_a75c29b1-ffe1-455e-bf61-23cba5e8e6af became leader
kube-system          3m22s       Normal    LeaderElection            endpoints/kube-scheduler                       kind-control-plane_a75c29b1-ffe1-455e-bf61-23cba5e8e6af became leader
default              3m18s       Normal    NodeHasSufficientPID      node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientPID
default              3m18s       Normal    NodeAllocatableEnforced   node/kind-control-plane                        Updated Node Allocatable limit across pods
default              3m18s       Normal    NodeHasNoDiskPressure     node/kind-control-plane                        Node kind-control-plane status is now: NodeHasNoDiskPressure
default              3m18s       Normal    NodeHasSufficientMemory   node/kind-control-plane                        Node kind-control-plane status is now: NodeHasSufficientMemory
default              3m18s       Normal    Starting                  node/kind-control-plane                        Starting kubelet.
kube-system          3m5s        Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-dn288
local-path-storage   2m48s       Warning   FailedScheduling          pod/local-path-provisioner-547f784dff-x7wtc    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          3m5s        Normal    SuccessfulCreate          daemonset/kube-proxy                           Created pod: kube-proxy-8w89p
local-path-storage   3m5s        Normal    SuccessfulCreate          replicaset/local-path-provisioner-547f784dff   Created pod: local-path-provisioner-547f784dff-x7wtc
kube-system          2m48s       Warning   FailedScheduling          pod/coredns-f9fd979d6-mwbrk                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          3m5s        Normal    ScalingReplicaSet         deployment/coredns                             Scaled up replica set coredns-f9fd979d6 to 2
local-path-storage   3m5s        Normal    ScalingReplicaSet         deployment/local-path-provisioner              Scaled up replica set local-path-provisioner-547f784dff to 1
kube-system          3m5s        Normal    SuccessfulCreate          daemonset/kindnet                              Created pod: kindnet-lvc9p
default              3m5s        Normal    RegisteredNode            node/kind-control-plane                        Node kind-control-plane event: Registered Node kind-control-plane in Controller
kube-system          3m5s        Normal    SuccessfulCreate          replicaset/coredns-f9fd979d6                   Created pod: coredns-f9fd979d6-mwbrk
kube-system          3m5s        Warning   NodeNotReady              pod/kube-apiserver-kind-control-plane          Node is not ready
kube-system          3m5s        Normal    Scheduled                 pod/kube-proxy-8w89p                           Successfully assigned kube-system/kube-proxy-8w89p to kind-control-plane
kube-system          3m4s        Normal    Scheduled                 pod/kindnet-lvc9p                              Successfully assigned kube-system/kindnet-lvc9p to kind-control-plane
kube-system          3m4s        Normal    Pulled                    pod/kindnet-lvc9p                              Container image "docker.io/kindest/kindnetd:v20210326-1e038dc5" already present on machine
kube-system          2m48s       Warning   FailedScheduling          pod/coredns-f9fd979d6-dn288                    0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
kube-system          3m4s        Normal    Pulled                    pod/kube-proxy-8w89p                           Container image "k8s.gcr.io/kube-proxy:v1.19.11" already present on machine
kube-system          3m2s        Normal    Started                   pod/kube-proxy-8w89p                           Started container kube-proxy
default              3m2s        Normal    Starting                  node/kind-control-plane                        Starting kube-proxy.
kube-system          3m2s        Normal    Created                   pod/kube-proxy-8w89p                           Created container kube-proxy
kube-system          3m1s        Normal    Created                   pod/kindnet-lvc9p                              Created container kindnet-cni
kube-system          3m1s        Normal    Started                   pod/kindnet-lvc9p                              Started container kindnet-cni
default              2m48s       Normal    NodeReady                 node/kind-control-plane                        Node kind-control-plane status is now: NodeReady
kube-system          2m43s       Normal    Scheduled                 pod/coredns-f9fd979d6-dn288                    Successfully assigned kube-system/coredns-f9fd979d6-dn288 to kind-control-plane
kube-system          2m43s       Normal    Scheduled                 pod/coredns-f9fd979d6-mwbrk                    Successfully assigned kube-system/coredns-f9fd979d6-mwbrk to kind-control-plane
kube-system          2m42s       Normal    Pulled                    pod/coredns-f9fd979d6-dn288                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          2m42s       Normal    Pulled                    pod/coredns-f9fd979d6-mwbrk                    Container image "k8s.gcr.io/coredns:1.7.0" already present on machine
kube-system          2m41s       Normal    Created                   pod/coredns-f9fd979d6-dn288                    Created container coredns
kube-system          2m41s       Normal    Started                   pod/coredns-f9fd979d6-dn288                    Started container coredns
kube-system          2m41s       Normal    Created                   pod/coredns-f9fd979d6-mwbrk                    Created container coredns
kube-system          2m41s       Normal    Started                   pod/coredns-f9fd979d6-mwbrk                    Started container coredns
local-path-storage   2m39s       Normal    Scheduled                 pod/local-path-provisioner-547f784dff-x7wtc    Successfully assigned local-path-storage/local-path-provisioner-547f784dff-x7wtc to kind-control-plane
local-path-storage   2m38s       Normal    Pulled                    pod/local-path-provisioner-547f784dff-x7wtc    Container image "docker.io/rancher/local-path-provisioner:v0.0.14" already present on machine
local-path-storage   2m36s       Normal    Created                   pod/local-path-provisioner-547f784dff-x7wtc    Created container local-path-provisioner
local-path-storage   2m36s       Normal    Started                   pod/local-path-provisioner-547f784dff-x7wtc    Started container local-path-provisioner
local-path-storage   2m36s       Normal    LeaderElection            endpoints/rancher.io-local-path                local-path-provisioner-547f784dff-x7wtc_dc647b7e-1fd1-427e-af4a-2eaaee357953 became leader
```

</details>

**Comment by iamtodor** [comment]
@BenTheElder would you approve if I submit a PR for the line https://github.com/kubernetes-sigs/kind/blob/main/site/content/docs/user/configuration.md?plain=1#L286 I would like to make a note to be bold: NOTE -> **NOTE**

**Comment by iamtodor** [comment]
After I add a proper mount as it was described here https://github.com/kubernetes-sigs/kind/issues/2669#issuecomment-1065343510
I am still not able to make it run. For some reason.
Here are the logs from `kind export logs`
[docker-info.txt](https://github.com/kubernetes-sigs/kind/files/8234529/docker-info.txt)
[kind-control-plane.zip](https://github.com/kubernetes-sigs/kind/files/8234530/kind-control-plane.zip)
[kind-version.txt](https://github.com/kubernetes-sigs/kind/files/8234531/kind-version.txt)

**Comment by iamtodor** [comment]
@BenTheElder could you please take a look? :)

**Comment by BenTheElder** [comment]
Looking at the logs in https://github.com/kubernetes-sigs/kind/issues/2669#issuecomment-1065377951 I see lots of non-system pods installed, and all the system pods appear to have logs so they must be scheduled.

I see kube-scheduler crashed due to:

> 2022-03-11T17:54:19.955986Z stderr F E0311 17:54:19.955832       1 reflector.go:127] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"


kind by default is not setting up anything related to extension-apiserver

**Comment by BenTheElder** [comment]
It looks like kube-scheduler restarted in a new pod and didn't crash that time.

**Comment by iamtodor** [comment]
@BenTheElder thank you for taking a look! Could you please clarify what did I do wrong or misconfigured? Or what should I do in order to make it work properly? Cause currently, I don't understand what to do :D

**Comment by BenTheElder** [comment]
I'm not sure I understand what you are trying to resolve currently 🤔

**Comment by BenTheElder** [comment]
(sorry hit that on accident)

AFAICT pods *are* scheduling in that cluster other than the odd initial crash. I can't tell exactly how that occured but also it seems to have sorted itself out.

**Comment by BenTheElder** [comment]
Do we have any further follow up here?

**Comment by iamtodor** [comment]
@BenTheElder thank you for your attention here. I'm currently not working on this, so I'm not able to provide any updates
