### ISSUE TITLE
Intermittent coredns failure

### ISSUE THREAD

**Issue by thesse1** [kubernetes-sigs/kind#3984]
**What happened**:

I am running KIND in Podman Desktop for Windows. I am deploying a pod with a single container running the IBM webMethods Edge Server (ibmwebmethods.azurecr.io/webmethods-edge-runtime:11.0.11). The container shows intermittent behavior. For some time, everything is working well, but sometimes it fails to connect to the webMethods control plane. In the log, it reports failures to resolve hostnames. I have found multiple errors in the logs of the two coredns pods, cf. attachment.

**What you expected to happen**:

The pod should be able to contact the control plane.

**How to reproduce it (as _minimally_ and precisely as possible)**:

Start a pod based on ibmwebmethods.azurecr.io/webmethods-edge-runtime:11.0.11.

**Anything else we need to know?**:

It is working well on minikube.

**Environment:**

- kind version: (use `kind version`): kind v0.29.0 go1.24.2 windows/amd64
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):
Client:
  APIVersion: 5.5.2
  Built: 1750781584
  BuiltTime: Tue Jun 24 18:13:04 2025
  GitCommit: e7d8226745ba07a64b7176a7f128e4ef53225a0e
  GoVersion: go1.24.4
  Os: windows
  OsArch: windows/amd64
  Version: 5.5.2
host:
  arch: amd64
  buildahVersion: 1.40.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 96.88
    systemPercent: 1.09
    userPercent: 2.03
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "41"
  eventLogger: journald
  freeLocks: 2042
  hostname: THESSE
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.6.87.2-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 4712808448
  memTotal: 16055980032
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.15.0-1.fc41.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.15.0
    package: netavark-1.15.2-1.fc41.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.15.2
  ociRuntime:
    name: crun
    package: crun-1.22-1.fc41.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.22
      commit: 4de19b63a85efd9ea8503452179c371181750130
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250611.g0293c6f-1.fc41.x86_64
    version: |
      pasta 0^20250611.g0293c6f-1.fc41.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 0h 50m 53.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.additionalImageStores:
    - /usr/lib/containers/storage
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 9087844352
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.5.2
  BuildOrigin: Fedora Project
  Built: 1750723200
  BuiltTime: Tue Jun 24 02:00:00 2025
  GitCommit: e7d8226745ba07a64b7176a7f128e4ef53225a0e
  GoVersion: go1.23.10
  Os: linux
  OsArch: linux/amd64
  Version: 5.5.2
- OS (e.g. from `/etc/os-release`): Windows 11
- Kubernetes version: (use `kubectl version`):
Client Version: v1.33.3
Kustomize Version: v5.6.0
Server Version: v1.33.1
- Any proxies or other special environment settings?: No

[kind_coredns_logs.txt](https://github.com/user-attachments/files/21696866/kind_coredns_logs.txt)

**Comment by stmcginnis** [comment]
I vaguely remember there being a DNS issue that was fixed. Do you recall @aojea?

**Comment by aojea** [comment]
what is your resolv.conf in your containers?

```
coredns-674b8bbfcf-kx7vp [ERROR[] plugin/errors: 2 contour.dns.podman. AAAA: dial udp [fc00:f853:ccd:e793::1]:53: connect: network is unreachable
coredns-674b8bbfcf-kx7vp [ERROR] plugin/errors: 2 contour. AAAA: read udp 10.244.0.4:59008->10.89.0.1:53: i/o timeout
```

there are failures to connect to the upstream dns servers.

This environment with windows, podman, ... is really not well supported

**Comment by thesse1** [comment]
```
[sagadmin@ert-5557df499d-xtw8q etc]$ cat resolv.conf
search webm-dev.svc.cluster.local svc.cluster.local cluster.local dns.podman fritz.box
nameserver 10.96.0.10
options ndots:5
```

@stmcginnis, @aojea, thanks for looking into this!

**Comment by aojea** [comment]
the one in the kind container, also you need to troubleshoot from the kind container the dns to see if there are packet loss 

`docker exec -it kind-control-plane bash`

You can install `dig` on the kind container `apt-get update && apt-get install dnsutils` and do several request in a loop to check if there are packet loss between kind and the host

**Comment by thesse1** [comment]
I do not see any errors when I execute dig (multiple times) with one of the hostnames that are not resolved correctly in my application.

It always looks like this:

```
root@kind-cluster-control-plane:/# dig uhm.e2em-hybrid-az-eu.webmethods.io

; <<>> DiG 9.18.33-1~deb12u2-Debian <<>> uhm.e2em-hybrid-az-eu.webmethods.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38168
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;uhm.e2em-hybrid-az-eu.webmethods.io. IN        A

;; ANSWER SECTION:
uhm.e2em-hybrid-az-eu.webmethods.io. 211 IN A   104.18.34.168
uhm.e2em-hybrid-az-eu.webmethods.io. 211 IN A   172.64.153.88

;; Query time: 3 msec
;; SERVER: fc00:f853:ccd:e793::1#53(fc00:f853:ccd:e793::1) (UDP)
;; WHEN: Mon Aug 11 09:38:11 UTC 2025
;; MSG SIZE  rcvd: 96
```

@stmcginnis, @aojea, thanks for your help!

**Comment by BenTheElder** [comment]
YMMV but disabling the additional search paths may be helpful if they're not being used:
https://github.com/kubernetes-sigs/kind/blob/283d3d3ef28326aab988d881b9e86eaf205ca46b/hack/ci/e2e-k8s.sh#L167

This feature is not yet suitably documented, but it can help reduce load / flakes.

**Comment by thesse1** [comment]
Hi @BenTheElder, thanks for your comment. Is this something I can do, or is it a hint for the KIND developers? If it is something I could do, I would please need some more help. What exactly can I change in my configuration? Thanks!

**Comment by BenTheElder** [comment]
@thesse1, sorry that was a quick and vague pointer between K8s 1.34 RC issues...

That's a config option (see the surrounding context) https://kind.sigs.k8s.io/docs/user/configuration/

You can set it like this:

1. `kind-config.yaml`:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # disable inheriting DNS search paths from the host
  dnsSearch: []
```

2. `kind create cluster --config=./kind-config.yaml`

**Comment by thesse1** [comment]
[kind_coredns_logs.txt](https://github.com/user-attachments/files/21728349/kind_coredns_logs.txt)
@BenTheElder, thanks for the description. I have started a new KIND cluster with the kind-config.yaml as per your comment. Unfortunately, it did not help. I still see the errors in the coredns logs, cf. attachment - even before I start my webMethods Edge Server pod.

**Comment by thesse1** [comment]
Update:

- When I start the KIND cluster on the command line with kind create cluster --config=./kind-config.yaml, it is working fine.
- When I start it from the Podman Desktop for Windows dashboard (Settings -> Kind -> Create new) with default settings, it shows the behavior described above.
- When I disable the ingress controller when starting the KIND cluster, it is also working fine

<img width="363" height="55" alt="Image" src="https://github.com/user-attachments/assets/056b9cd3-5ac6-4b2b-bd3f-04bd1b07eef1" />

It seems the error is caused by the Contour ingress controller (which I do not need for my use case). Thanks for your support!

**Comment by stmcginnis** [comment]
> When I start it from the Podman Desktop for Windows dashboard (Settings -> Kind -> Create new) 

Ah, I wasn't aware Podman Desktop added that directly in to the project. This is actually sounding like a bug with Podman Desktop, not kind, so it may be good to open an issue with them.

**Comment by thesse1** [comment]
Done: https://github.com/podman-desktop/podman-desktop/issues/13568

Thanks for your help!

**Comment by BenTheElder** [comment]
Aha! Thanks.

BTW, I don't know what podman desktop is doing, but https://kind.sigs.k8s.io/docs/user/loadbalancer/ is a good option combined with BYO ingress using the loadbalancer.

We currently have docs for ingress nginx at https://kind.sigs.k8s.io/docs/user/ingress/
... which will probably switch to https://github.com/kubernetes-sigs/ingate when it's more mature.
